name: Run Python Script

on:
  schedule:
    # Executa a cada dia às 2:00 AM (UTC)
    - cron: '0 2 * * 6'
  # Gatilho manual (opcional, para rodar no GitHub também)
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # 1. Verifique o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura o Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # ou a versão que você está usando

      # 3. Instala as dependências (caso tenha um requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Executa o script Python
      - name: Run Python script
        run: |
          python ru.py --modo week --user ${{secrets.SIGAA_USER}} --password ${{secrets.SIGAA_SENHA}}
